services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT:-80}:80"
        environment:
            - NODE_ENV=production
        container_name: eu-tirads-prod
